Description: "SSM State Manager Association with Ansible S3 Source"
Parameters:

  pPlayBookUri:
    Type: 'String'
    Description: specify path of the playbook file or the directory for ssm to download

Resources:

  AnsibleAssociation:
    Type: AWS::SSM::Association
    Properties:
      AssociationName: "DoD-Banner"
      # Specify using the AWS-ApplyAnsiblePlaybooks
      Name: AWS-ApplyAnsiblePlaybooks
      WaitForSuccessTimeoutSeconds: 300
      # Targeting Instance by tagging
      Targets:
        - Key: tag:ansible-role
          Values:
            - banner-dod
      ## how often state association should run checking for compliance
      ScheduleExpression: rate(30 minutes)
      Parameters:
        # Getting an Ansible Playbook from a S3 Location
        SourceType:
          - 'S3'
        # You can also store and download Ansible playbooks in Amazon S3 as either a single .zip file
        # or a directory structure. To download content from Amazon S3, specify the path to the file.
        SourceInfo:
          - !Sub |
              {"path":"${pPlayBookUri}"}
        # Installing Ansible and its dependencies
        InstallDependencies:
          - 'True'
        # Playbook file we want to run
        PlaybookFile:
          - 's3-local.yml'
        ExtraVariables:
          - 'SSM=True'
        Check:
          - 'False'
        Verbose:
          - '-v'
