Description: "Deploy Single EC2 Linux Instance"
Parameters:

  pPlayBookUri:
    Type: 'String'
    Description: specify path of the playbook file or the directory for ssm to download

Resources:

  SSMAssocLogs:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "ssm-github-logs-${AWS::AccountId}-${AWS::Region}"

  AnsibleAssociation:
    Type: AWS::SSM::Association
    Properties:
      # Here using the AWS-ApplyAnsiblePlaybooks
      Name: AWS-ApplyAnsiblePlaybooks
      WaitForSuccessTimeoutSeconds: 300
      # Targeting Instance by InstanceId passed from the Logical ID of Instance being created
      # in CloudFormation
      Targets:
        - Key: tag:ansible-source
          Values:
            - 's3'
        - Key: tag:role
          Values:
            - 'banner-dod'
      OutputLocation:
        S3Location:
          OutputS3BucketName: !Sub ssm-logs-${AWS::AccountId}-${AWS::Region}
          OutputS3KeyPrefix: 's3/logs/'
      Parameters:
        # Getting an Ansible Playbook from a GitHub Location
        SourceType:
          - 'GitHub'
        # You can also store and download Ansible playbooks in Amazon S3 as either a single .zip file
        # or a directory structure. To download content from Amazon S3, specify the path to the file.
        SourceInfo:
          -  !Sub |
              {
                Path: "${pPlayBookUri}""
              }
        # Installing Ansible and its dependencies
        InstallDependencies:
          - 'True'
        # Playbook file we want to run
        PlaybookFile:
          - 's3-local.yml'
        ExtraVariables:
          - 'SSM=True'
        Check:
          - 'False'
        Verbose:
          - '-v'
