name: Prod Branch Deploy

on:
  push:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: ${{ secrets.REGION }}
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  ## TARGET BUCKET
  AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}

jobs:

  push-dev:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_REGION: ${{ secrets.REGION }}
        SOURCE_DIR: 'ansible'
        DEST_DIR: "production/ansible"
