name: Prod Branch Deploy

on:
  push:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: ${{ secrets.REGION }}
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCOUNT_ROLE: ${{ secrets.AWS_DEPLOY_ROLE }}

  ## TARGET BUCKET
  AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}

jobs:

  push-dev:
    name: Build & Push
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
        role-session-name: GADemoAnsibleProd
    - name: Copy Ansible Playbook ot S3
      run: |
        aws s3 sync ./ansible s3://${{ secrets.BUCKET_NAME }}/production --delete
