name: Test Branch Deploy

on:
  push:
    branches-ignore:
      - master

env:
  AWS_DEFAULT_REGION: ${{ secrets.REGION }}
  AWS_DEFAULT_OUTPUT: json


  ## TARGET BUCKET
  AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}

jobs:
  push-dev:
    name: Build & Push
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::774319035716:role/GADemo-Deploy
        role-session-name: GADemoAnsibleTest
        role-duration-seconds: '300'
    - name: Copy Ansible Playbook ot S3
      run: |
        aws s3 sync ./ansible s3://${{ secrets.BUCKET_NAME }}/test --delete
